# Generated by Django 4.0.2 on 2022-02-10 06:10

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page',
            new_name='title',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', tinymce.models.HTMLField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_content.page')),
            ],
        ),
    ]
