# Generated by Django 4.0.2 on 2022-02-10 06:50

from django.db import migrations, models
import django.db.models.deletion
import manage_content.models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_content', '0002_rename_page_page_title_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to=manage_content.models.user_directory_path)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manage_content.post')),
            ],
            options={
                'verbose_name': 'postgallery',
                'verbose_name_plural': 'post gallery',
            },
        ),
    ]
