# Generated by Django 4.0.2 on 2022-02-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_content', '0003_postgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
    ]
