# Generated by Django 4.0.2 on 2022-02-12 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_content', '0004_post_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['page', 'order']},
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='manage_content.post'),
        ),
    ]
